# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "INPUTSERVERNAME"
public_baseurl: "https://INPUTSERVERNAME/"
pid_file: /data/homeserver.pid
listeners:
  - port: 8443
    bind_addresses:
      - 172.30.5.2
      - 127.0.0.1
      - ::1
    resources:
    - compress: false
      names:
      - client
      #- federation
    tls: true
    type: http
    x_forwarded: true
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
allowed_avatar_mimetypes:
- image/png
- image/jpeg
- image/gif
- image/bmp
- image/avif
- image/svg+xml
- image/tiff
- image/webp
federation_domain_whitelist: []
# the TLS config assumes a symlink (or just copy) from /etc/letsencrypt/live/INPUTSERVERNAME/fullchain.pem | privkey.key, which is generated by Certbot
tls_certificate_path: /data/fullchain.pem
tls_private_key_path: /data/privkey.pem
log_config: "/data/homeserver.log.config"
media_store_path: /data/media_store
registration_shared_secret: "REGISTRATIONSECRET"
#enable_registration_captcha: true
#recaptcha_public_key: "RECAPTCHAPUBLIC"
#recaptcha_private_key: "RECAPTCHAPRIVATE"
report_stats: false
macaroon_secret_key: "MACAROONSECRET"
form_secret: "FORMSECRET"
signing_key_path: "/data/INPUTSERVERNAME.signing.key"
serve_server_wellknown: true
require_auth_for_profile_requests: true
trusted_key_servers: []
#trusted_key_servers:
#  - server_name: "matrix.org"


# vim:ft=yaml
